baseURL = "/"
languageCode = "en-us"
title = "chatbx.eu"
themesDir = "themes"
theme = "hugo-whisper-theme"
publishdir = "/var/www/chatbx.eu/www.chatbx.eu/public/"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 0

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Getting Started"
    url = "/documentation/getting_started"
    weight = 2

[[menu.main]]
    name = "Documentation"
    url = "/documentation/"
    weight = 3

[[menu.main]]
    name = "Account Registration"
    url = "https://accounts.chatbx.eu/"
    weight = 4

[[menu.main]]
    name = "Web Client"
    url = "https://web.chatbx.eu/"
    weight = 5

[params]
  homepage_button_link = '/documentation/getting_started'
  homepage_button_text = 'Get Started'
  homepage_intro = 'Decentralized Instant Messaging with XMPP.'
  #homepage_image = '/chatbx.png'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "chatbx.eu: Decentralized Instant Messaging with XMPP"
    meta_og_title = "chatbx.eu"
    meta_og_type = "website"
    meta_og_url = "https://www.chatbx.eu/"
    meta_og_image = "chatbx.png"
    meta_og_description = "chatbx.eu: Decentralized Instant Messaging with XMPP"

  [params.logo]
      mobile = "chatbx.png"
      standard  = "chatbx.png"
